id: I47C1A5DA
legacy_id: P007966
ocr_import_info:
  bdrc_scan_id: W3CN3381
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T06:20:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:35:49.733524+00:00'
last_modified: 2022-09-03 21:42:04.471648
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3381
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3381
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒྲུབ་ཐབས་རིན་པོ་ཆེ་ཀུན་ལས་བཏུས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.8807089925001075
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3CN20886:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20886
      total_pages: 833
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN20886.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8298850787880269
    legacy_id: v006
  I3CN20887:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20887
      total_pages: 915
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN20887.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9032568040698932
    legacy_id: v007
  I3CN20881:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20881
      total_pages: 831
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN20881.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8467013435231896
    legacy_id: v001
  I3CN20883:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20883
      total_pages: 787
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN20883.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9064044272932943
    legacy_id: v003
  I3CN20882:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20882
      total_pages: 838
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN20882.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8566688074439166
    legacy_id: v002
  I3CN20891:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20891
      total_pages: 855
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3CN20891.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.88001745000432
    legacy_id: v011
  I3CN20892:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20892
      total_pages: 1035
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I3CN20892.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9198242734381633
    legacy_id: v012
  I3CN20894:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20894
      total_pages: 837
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I3CN20894.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8432642848378793
    legacy_id: v014
  I3CN20888:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20888
      total_pages: 827
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3CN20888.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.861855525508035
    legacy_id: v008
  I3CN20890:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20890
      total_pages: 847
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3CN20890.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8642972496938895
    legacy_id: v010
  I3CN20893:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20893
      total_pages: 1051
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I3CN20893.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9072068168754068
    legacy_id: v013
  I3CN20885:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20885
      total_pages: 861
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN20885.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9131127809766879
    legacy_id: v005
  I3CN20884:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20884
      total_pages: 831
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN20884.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9052333522629764
    legacy_id: v004
  I3CN20889:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN20889
      total_pages: 831
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3CN20889.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9094602575201554
    legacy_id: v009
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
