id: I47C1A5DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:29:14+00:00'
last_modified: '2022-06-09T08:05:44.892088+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3381
  title: སྒྲུབ་ཐབས་རིན་པོ་ཆེ་ཀུན་ལས་བཏུས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AF84:
      image_group_id: I3CN20881
      title: Volume 1 of sgrub thabs rin po che kun las btus pa/
      total_pages: 831
      order: 1
      base_file: AF84.txt
    9B90:
      image_group_id: I3CN20882
      title: Volume 2 of sgrub thabs rin po che kun las btus pa/
      total_pages: 838
      order: 2
      base_file: 9B90.txt
    21BF:
      image_group_id: I3CN20883
      title: Volume 3 of sgrub thabs rin po che kun las btus pa/
      total_pages: 787
      order: 3
      base_file: 21BF.txt
    0BA0:
      image_group_id: I3CN20884
      title: Volume 4 of sgrub thabs rin po che kun las btus pa/
      total_pages: 831
      order: 4
      base_file: 0BA0.txt
    94CC:
      image_group_id: I3CN20885
      title: Volume 5 of sgrub thabs rin po che kun las btus pa/
      total_pages: 861
      order: 5
      base_file: 94CC.txt
    2F1A:
      image_group_id: I3CN20886
      title: Volume 6 of sgrub thabs rin po che kun las btus pa/
      total_pages: 833
      order: 6
      base_file: 2F1A.txt
    '9293':
      image_group_id: I3CN20887
      title: Volume 7 of sgrub thabs rin po che kun las btus pa/
      total_pages: 915
      order: 7
      base_file: 9293.txt
    B742:
      image_group_id: I3CN20888
      title: Volume 8 of sgrub thabs rin po che kun las btus pa/
      total_pages: 827
      order: 8
      base_file: B742.txt
    A942:
      image_group_id: I3CN20889
      title: Volume 9 of sgrub thabs rin po che kun las btus pa/
      total_pages: 831
      order: 9
      base_file: A942.txt
    7DAB:
      image_group_id: I3CN20890
      title: Volume 10 of sgrub thabs rin po che kun las btus pa/
      total_pages: 847
      order: 10
      base_file: 7DAB.txt
    948B:
      image_group_id: I3CN20891
      title: Volume 11 of sgrub thabs rin po che kun las btus pa/
      total_pages: 855
      order: 11
      base_file: 948B.txt
    '6688':
      image_group_id: I3CN20892
      title: Volume 12 of sgrub thabs rin po che kun las btus pa/
      total_pages: 1035
      order: 12
      base_file: 6688.txt
    97ED:
      image_group_id: I3CN20893
      title: Volume 13 of sgrub thabs rin po che kun las btus pa/
      total_pages: 1051
      order: 13
      base_file: 97ED.txt
    0FB3:
      image_group_id: I3CN20894
      title: Volume 14 of sgrub thabs rin po che kun las btus pa/
      total_pages: 837
      order: 14
      base_file: 0FB3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
