id: P007966
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3381
  title: སྒྲུབ་ཐབས་རིན་པོ་ཆེ་ཀུན་ལས་བཏུས་པ།
  author: ''
  volumes:
    94a36758101e4417805700440ab83765:
      image_group_id: I3CN20881
      title: Volume 1 of sgrub thabs rin po che kun las btus pa/
      volume_number: 1
      total_pages: 831
      base_file: v001.txt
    a60c91f8ae344abdaaa53bb59d2cd953:
      image_group_id: I3CN20882
      title: Volume 2 of sgrub thabs rin po che kun las btus pa/
      volume_number: 2
      total_pages: 838
      base_file: v002.txt
    69264ab7f2224a0abf282ce35351e12c:
      image_group_id: I3CN20883
      title: Volume 3 of sgrub thabs rin po che kun las btus pa/
      volume_number: 3
      total_pages: 787
      base_file: v003.txt
    a652b4f634994a0d82551517bab0b811:
      image_group_id: I3CN20884
      title: Volume 4 of sgrub thabs rin po che kun las btus pa/
      volume_number: 4
      total_pages: 831
      base_file: v004.txt
    5466bff0dc224879980a27ee579a6f3c:
      image_group_id: I3CN20885
      title: Volume 5 of sgrub thabs rin po che kun las btus pa/
      volume_number: 5
      total_pages: 861
      base_file: v005.txt
    18e22c69609d486fb1e096d76996baa3:
      image_group_id: I3CN20886
      title: Volume 6 of sgrub thabs rin po che kun las btus pa/
      volume_number: 6
      total_pages: 833
      base_file: v006.txt
    aac189410d504904b833317be924534d:
      image_group_id: I3CN20887
      title: Volume 7 of sgrub thabs rin po che kun las btus pa/
      volume_number: 7
      total_pages: 915
      base_file: v007.txt
    9a38f9fa40d148c9ba6ab6425bb8849c:
      image_group_id: I3CN20888
      title: Volume 8 of sgrub thabs rin po che kun las btus pa/
      volume_number: 8
      total_pages: 827
      base_file: v008.txt
    bcd9026593524191838e08b4b09b387e:
      image_group_id: I3CN20889
      title: Volume 9 of sgrub thabs rin po che kun las btus pa/
      volume_number: 9
      total_pages: 831
      base_file: v009.txt
    d87f863398b44292a79a1cb207f9ea2c:
      image_group_id: I3CN20890
      title: Volume 10 of sgrub thabs rin po che kun las btus pa/
      volume_number: 10
      total_pages: 847
      base_file: v010.txt
    6331ff5331884042aed2d758cff8bdd9:
      image_group_id: I3CN20891
      title: Volume 11 of sgrub thabs rin po che kun las btus pa/
      volume_number: 11
      total_pages: 855
      base_file: v011.txt
    abd3d53d0b204423b5cc900e3e6ae624:
      image_group_id: I3CN20892
      title: Volume 12 of sgrub thabs rin po che kun las btus pa/
      volume_number: 12
      total_pages: 1035
      base_file: v012.txt
    bf9b37c5d81d41b7ba45c1e06d75adf2:
      image_group_id: I3CN20893
      title: Volume 13 of sgrub thabs rin po che kun las btus pa/
      volume_number: 13
      total_pages: 1051
      base_file: v013.txt
    a329635540754b1e93711fb168aea5c7:
      image_group_id: I3CN20894
      title: Volume 14 of sgrub thabs rin po che kun las btus pa/
      volume_number: 14
      total_pages: 837
      base_file: v014.txt
ebook_metadata:
  title: སྒྲུབ་ཐབས་རིན་པོ་ཆེ་ཀུན་ལས་བཏུས་པ།
  author: ''
  sku: P007966
  cover: cover.jpg
  layers:
  - pagination
