id: P007966
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3381
  title: སྒྲུབ་ཐབས་རིན་པོ་ཆེ་ཀུན་ལས་བཏུས་པ།
  author: ''
  volumes:
    d86791430a834940842ab63343e8d8b3:
      image_group_id: I3CN20881
      title: ''
      volume_number: 1
      total_pages: 831
    3b50c795e90d4802bbbc7ee7bfbeb679:
      image_group_id: I3CN20882
      title: ''
      volume_number: 2
      total_pages: 838
    25701d706c264de6ab8c42d0f91c25ec:
      image_group_id: I3CN20883
      title: ''
      volume_number: 3
      total_pages: 787
    c3dd68843f7a48b8b44aa79b9e1a26a3:
      image_group_id: I3CN20884
      title: ''
      volume_number: 4
      total_pages: 831
    7351545c4e3a4340a0134596e6a30d4c:
      image_group_id: I3CN20885
      title: ''
      volume_number: 5
      total_pages: 861
    bd62f02fef664b92885a3cc6796c4210:
      image_group_id: I3CN20886
      title: ''
      volume_number: 6
      total_pages: 833
    3b81ced78caf4080803ed4f207416bf1:
      image_group_id: I3CN20887
      title: ''
      volume_number: 7
      total_pages: 915
    25b326ef498140bfa9722726e7b8d21f:
      image_group_id: I3CN20888
      title: ''
      volume_number: 8
      total_pages: 827
    f7c6ab53db4e4387a178c5550fb93a22:
      image_group_id: I3CN20889
      title: ''
      volume_number: 9
      total_pages: 831
    9dbacf6d643f4d449a840f26cdcd469a:
      image_group_id: I3CN20890
      title: ''
      volume_number: 10
      total_pages: 847
    e912a826f5474ff5b1682dcdf9d177b3:
      image_group_id: I3CN20891
      title: ''
      volume_number: 11
      total_pages: 855
    f1cacff5c1df4775856312488f0ad2eb:
      image_group_id: I3CN20892
      title: ''
      volume_number: 12
      total_pages: 1035
    ae3091ad021f4ffd9dd46dfbeaeb8433:
      image_group_id: I3CN20893
      title: ''
      volume_number: 13
      total_pages: 1051
    8092348db3f449b0b0e66a730ec93611:
      image_group_id: I3CN20894
      title: ''
      volume_number: 14
      total_pages: 837
ebook_metadata:
  title: སྒྲུབ་ཐབས་རིན་པོ་ཆེ་ཀུན་ལས་བཏུས་པ།
  author: ''
  sku: P007966
  cover: cover.jpg
  layers:
  - pagination
